version: '3.8'
services:
  db:
    image: bitnami/mariadb:latest
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./volumes/mariadb:/bitnami/mariadb
    networks:
      - universal
  app:
    build:
      args:
        user: 1000
        uid: 1000
        UPLOAD_MAX_FILESIZE: ${UPLOAD_MAX_FILESIZE}
        POST_MAX_SIZE: ${POST_MAX_SIZE}
      context: ./
      dockerfile: Dockerfile
    image: universal-lite
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - universal
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./src/Kernel/Conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/Kernel/Conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/Kernel/Conf/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./src/Kernel/Conf/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./volumes/nginx:/etc/nginx/cache
    networks:
      - universal

networks:
  universal:
    driver: bridge
